### ISSUE TITLE
Handling Rails HEAD 204 on update

### ISSUE THREAD

**Issue by kaisersly** [js-data/js-data-http#16]
I'm using Rails as my backend. It responds to successful PATCH/PUT request with a HEAD 204 (NO CONTENT).

When js-data gets the response, the data.data properties is "" and it triggers an error when js-data tries to inject it.

What is the proper way to handle this case (apart from tweaking Rails behaviour) ?

**Comment by jmdobry** [comment]
Yes, you can use the `cacheResponse: false` and js-data won't try to inject the response into the store.

**Comment by kaisersly** [comment]
Yeah, i figured this out this afternoon after some research.

As Rails is used by many people, don't you think we could document this problem w/ solution somewhere ? I could write a small post (with code snippets) if you want.

**Comment by jmdobry** [comment]
Yeah, I could put a link to your post in the docs

**Comment by kaisersly** [comment]
Ok i'll write it tomorrow then.

I have a side question (still Rails related) : I used an interceptor to change PUT request to PATCH request. You say that it is possible to configure it in DS#defineResource : How ?

**Comment by jmdobry** [comment]
To configure it for a specific method, you'll either need to create your own static method on the resource that wraps `DS#save` or `DS#update` and changes the method to PATCH in the options, or wait for 2.x where you can do a little AOP to configure the methods individually.

**Comment by kaisersly** [comment]
Ok thanks for your answers and your work !

**Comment by jmdobry** [comment]
@kaisersly Your article, with a few minor additions/corrections: http://www.js-data.io/blog/handling-rails-head-204-on-update

**Comment by kaisersly** [comment]
Ok cool, hope this will help others.

**Comment by itsmechlark** [comment]
@jmdobry  Is there any other solution rather manually injecting the resource. Hassle if we maintain many resources. Thanks.

**Comment by jmdobry** [comment]
@itsmechlark This should work just fine:

```javascript
var Foo = DS.defineResource({
  name: 'foo',
  cacheResponse:false
});

var foo = Foo.inject({ id: 1, name: 'bar' });
foo.name; // "bar"
foo.name = 'beep';
foo.name; // "beep"
foo.DSSave().then(function () {
  foo.name; // "beep"
  Foo.get(1).name; // "beep"
  foo.name === Foo.get(1).name; // true
  foo === Foo.get(1); // true
});
```

**Comment by itsmechlark** [comment]
BTW, I'm using [js-data/js-data-angular](https://github.com/js-data/js-data-angular). 

```Coffee
Document.find($routeParams.id).then (document)->
    document.DSUpdate(title: "Test").then ->
      console.log(Document.get(document.id))
```

It does send to my API, and didn't update from storage.

**Comment by jmdobry** [comment]
> didn't update from storage

Unlike in my example, you used `DS#update`, that's why.

**Comment by itsmechlark** [comment]
Thanks. I fix this problem by overriding the rails responders:

```ruby
class Api::V1::ApiController < ActionController::API
  self.responder = ::ApiResponder
end

class ApiResponder < ActionController::Responder
  include Responders::HttpCacheResponder

  def api_behavior
    fail MissingRenderer.new(format) unless has_renderer?

    if get?
      display resource
    elsif post?
      display resource, status: :created, location: api_location
    elsif patch? || put?
      display resource, status: :ok, location: api_location
    else
      head :no_content
    end
  end
end
```
