### ISSUE TITLE
Angular/HTTP: Allow computed properties without using data attributes from the service

### ISSUE THREAD

**Issue by ajbogh** [js-data/js-data-http#19]
I would like to be able to add a computed property to the object without having to use one of the properties from the response object. An example of this is below.

    computed: {
        type: [null, function(){ //use null? Maybe there's a better way?
            return "gift";
        }],
    }

This way all items of this response get a static property assigned to them, in this case "gift".

In order to make this work I have to use any property except the ID in the function definition and just ignore the variable.

    computed: {
        type: ['someProperty', function(someProperty){
            return "gift";
        }],
    }

**Comment by jmdobry** [comment]
I'll take a look

**Comment by jmdobry** [comment]
I believe this has been fixed in one of the more recent versions of js-data.
