### ISSUE TITLE
DSHttpAdapter.POST does not pick DSHttpAdapter.defaults.basePath

### ISSUE THREAD

**Issue by mahadazad** [js-data/js-data-http#20]
I am using it with js-data-angular and when making request via the DSHttpAdapter.POST method it does not pickup the default basePath defined while configuration phase.

**Comment by mahadazad** [comment]
It seems like it does not respect any of the defaults set: basePath, deserialize, etc

**Comment by jmdobry** [comment]
The GET, PUT, POST, and DELETE methods are literally wrappers around $http.(get|put|post|delete) (or the corresponding axios methods). Right now they don't use the options that the find, findAll, etc. methods use. I've run into this myself recently, and I'm thinking about what to do about it

**Comment by mahadazad** [comment]
Well it would be nice if these methods could use the default settings. As there are sometimes situation when we don't need a resource, instead, just want to make a raw request. In my case I wanted to make a request to login my api to verify if the credentials were correct. There was no point to make a `login` type resource in this case.

**Comment by alexzaporozhets** [comment]
@jmdobry maybe you can suggest other way around to implement the login functionality?

**Comment by jmdobry** [comment]
I did: https://gist.github.com/jmdobry/a6f1858b494809eccf5e#file-user-js-L77
