### ISSUE TITLE
Add support for patch / patrial update method

### ISSUE THREAD

**Issue by facultymatt** [js-data/js-data-http#48]
If the API supports PATCH then it's ideal to use PATCH instead of PUT when updating a specific property or set of properties. This avoids the need for more complex serialize and deserialize logic, prevents unwanted properties from being sent to API, and gives precise control to the developer. 

A DSPatch method make a PATCH request with individual selected properties, and update only those properties on when model on success. 

For example: 

```
// single property
this.wheel.current_owner = 99;
this.wheen.patch('current_owner');
PATCH /wheels/1 {current_owner: 99}

// multiple
this.wheel.last_service = new Date();
this.wheel.patch(['current_owner', last_service]);
PATCH /wheels/1 {current_owner: 99, last_service: Date}
```

**Comment by jmdobry** [comment]
```js
this.wheel.current_owner = 99
// PATCH /wheels/1 { current_owner: 99 }
this.wheel.DSSave({ changesOnly: true, method: 'PATCH' }).then(function (wheel) {
  // send only selected fields
  // PATCH /wheels/1 { last_server: ..., current_owner: 77 }
  return this.wheel.DSUpdate({ last_service: new Date(), current_owner: 77 }, { method: 'PATCH' })
}).then(...)
```

**Comment by facultymatt** [comment]
Perfect - I will give this a try! Looks like it should solve my use case.

**Comment by facultymatt** [comment]
The above solution worked well. Thanks!
