### ISSUE TITLE
typescript definition file for js-data-http v3

### ISSUE THREAD

**Issue by nlac** [js-data/js-data-http#49]
Hi,
may i request to add ts definition files for js-http-data and the other adapters? For js-data v3, js-data.d.ts is already there in the /dist.

**Comment by jmdobry** [comment]
It's on my list of 100 things to do for js-data. Happy to accept pull requests.

**Comment by nlac** [comment]
Ok, created the js-data-http.d.ts file for v3 beta. May i put it into the /dist folder (as it is for js-data) before create the pull request?

**Comment by jmdobry** [comment]
Yes, that file will need to reside in the `dist/` folder.
