### ISSUE TITLE
Not testing for false with HttpAdapter option(s) "log"

### ISSUE THREAD

**Issue by rquast** [js-data/js-data-http#53]
https://js-data.slack.com/archives/js-data-http/p1466314357000009

this.adapter = new HttpAdapter({"log": false, "error": false}); - setting log to false in the config for js-data 3 causes this error..

"this.log.apply is not a function"

doesn't check for log being false first.

Problem is in utils mixin in js-data .. need to test for false this.log (or typeof === 'function') here:

https://github.com/js-data/js-data/blob/3.0.0-beta.7/src/utils.js#L1033

**Comment by jmdobry** [comment]
Fixed in js-data
