### ISSUE TITLE
responseError callback no longer includes the actual error response object from the server

### ISSUE THREAD

**Issue by omanizer** [js-data/js-data-http#60]
It's common for error responses returned from the server to contain a JSON object similar to this:

```
{
  "status": 400,
  "error": "You forgot to enter your name"
}
```

I've found it very useful in the past to do something like this when configuring the http adapter:

```
var httpAdapter = new JSDataHttp.HttpAdapter({
  responseError: function (response, config, options) {
    console.log('response error', response, config, options)
    if (response.status === 401) {
      // display login modal
    } else if (response.status === 426) {
      // Prompt user to refresh the page since the code is outdated
    } else {
      // Alert the user that there was an error with this request
    }
  }
})
```

While it's good practice to handle errors within the components of an application (and I do often), it's also nice to have this to notify a user whenever there is an error (in a Toast in the corner) and what the error was.  Mainly it's nice when a session expires and a 401 request is returned to be able to have a single place within the application to open the login dialog so a user can re-authenticate without losing all their work.

This has been working in the past but no longer does.  When I log what is passed into the responseError method in the latest version (3.0.0-rc.2) I see that it is just this, a regular old JS error:
`Error: Request failed with status code 400(…)`

Would be fantastic if response.status and response.data.error both existed still rather than just returning an instantiation of the Error class... or just the ability to get the response object that "errored" somehow.  Same story with the `error` method in the HttpAdapter configuration. 

Steps to reproduce:
1) Set up an environment with both JSData and JSDataHttp (3.0.0-rc.2)
2) When configuring HttpAdapter, include the above configuration for `responseError`
3) Make any request using JSData to an endpoint that returns an HTTP status code in the 400s or 500s and includes a JSON object in the body of the response.
4) Observe that the logged data from the console.log inside of responseError only has a vanilla JS Error object rather than the actual response object that it used to.
5) Downgrade JSDataHttp to (3.0.0-beta.8)
6) Re-run the same request
7) Observe that the first parameter of the responseError callback contains an object which has both `status` and `data` properties filled appropriately.

**Comment by jmdobry** [comment]
After looking through the code for handling an error response (which didn't change between 3.0.0-beta.8 and 3.0.0-rc.2) I can only conclude that something changed in `axios` itself that is causing this issue. Between 3.0.0-beta.8 and 3.0.0-rc.2 `axios` was upgraded from `0.12.0` to `0.13.1`. 😕

**Comment by omanizer** [comment]
Dang, I as afraid of that.  It seems those configuration options are passed directly to axios.  I'll file a issue with them on this.  Thanks for checking.

Are there any other options such as manually providing the older Axios library to JSData?

**Comment by jmdobry** [comment]
> Are there any other options such as manually providing the older Axios library to JSData?

Yes, load `js-data-fetch` instead (it's just `js-data-http` minus the bundled `axios`), and then give it the version of `axios` you want to use. See http://www.js-data.io/v3.0/docs/js-data-http#using-a-custom-http-library

**Comment by black-roland** [comment]
@omanizer You can find original response object in `err.response`. Please check out [enhanceError.js](https://github.com/mzabriskie/axios/blob/b8f6f5049cf3da8126a184b6b270316402b5b374/lib/core/enhanceError.js).

```
new HttpAdapter({
  responseError: (err, _config, _options) =>  {
    console.log(err.response.status, err.response);
  },
})
```

**Comment by omanizer** [comment]
You're correct!  I apologize, should have closed this weeks ago when I found that out. 👍🏻
