### ISSUE TITLE
Update axios compatibility to 0.15.x, separate as dependency.

### ISSUE THREAD

**Issue by calebroseland** [js-data/js-data-http#64]
We use `axios` and would like to take advantage of some newer features/updates in `js-data-http@3`. 
Most notably:  
- [0.15] [cancellation](https://github.com/mzabriskie/axios#cancellation) according to [proposal-cancelable-promises](https://github.com/tc39/proposal-cancelable-promises)
- [0.14?] Naming convention from `axios.GET()` to `axios.get()`. Just preferential. 

The second requires changes to the API, or at least additional lowercase methods, with uppercase methods still around for backwards compatibility.

Would also be great to be able to share the same `axios` module and save a few bytes. Kind of in the same way `Promise` is depended on, or was configurable in `js-data@2`. Yes, we can pass in an `http` option in the constructor, but `axios` is still baked in. Maybe a bring-your-own-http-lib build?

I would be more than willing to submit a PR, but wanted to check first if any of this would be in-line with the vision for the project.

Thanks!

**Comment by calebroseland** [comment]
Just in case it might help anyone, I was able to use `axios@0.15.3` with by creating a request interceptor that deletes `config.adapter //which is === 'http'`. This would cause an error if passed to `axios`. 

Might not be the cleanest, but works for now if you need cancellation.

```
const httpForAdapter = axios.create()
httpForAdapter.interceptors.request.use(function (config) {
  delete config.adapter
  return config
})

export const httpAdapter = new HttpAdapter({
  http: httpForAdapter
})
```

**Comment by kvandelden** [comment]
Awesome, thanks.
