### ISSUE TITLE
Adapter default basePath is taken instead of definition basePath

### ISSUE THREAD

**Issue by ScottTrenda** [js-data/js-data-http#70]
If `basePath` is defined on an adapter's defaults, then it is used for resolving all paths before a resource's `basePath` is referenced.

Basically this is the same issue as js-data/js-data#232 (and should have the same fix), but it pervades into js-data-angular, and occurs over a much larger set of instances.

**Comment by crobinson42** [comment]
@ScottTrenda v2.2.3 published ☝️ thx again. We're not going to be doing any more work on v2 so I recommend you upgrade to v3 asap 👍

**Comment by ScottTrenda** [comment]
Awesome, thank you. Could I please request a patch release of js-data-angular that uses js-data-http v2.2.3? Much appreciated!!

**Comment by crobinson42** [comment]
Can you PR the patch needed

**Comment by ScottTrenda** [comment]
I can try. It looks like v3.2.0 to v3.2.1 is just a simple upgrade of js-data-http to v2.2.2, so I'll take a look at what went into that and do the same.
